// Code generated by alioth-center/database-columns. DO NOT EDIT.
// Code generated by alioth-center/database-columns. DO NOT EDIT.
// Code generated by alioth-center/database-columns. DO NOT EDIT.

package model

type openairequestCols struct {
	ID                   string
	ClientID             string
	RequestID            string
	TraceID              string
	ModelID              string
	UserID               string
	RequestIP            string
	PromptTokenUsage     string
	CompletionTokenUsage string
	BalanceCost          string
	CreatedAt            string
}

var OpenaiRequestCols = &openairequestCols{
	ID:                   "id",
	ClientID:             "client_id",
	RequestID:            "request_id",
	TraceID:              "trace_id",
	ModelID:              "model_id",
	UserID:               "user_id",
	RequestIP:            "request_ip",
	PromptTokenUsage:     "prompt_token_usage",
	CompletionTokenUsage: "completion_token_usage",
	BalanceCost:          "balance_cost",
	CreatedAt:            "created_at",
}
