// Code generated by alioth-center/database-columns. DO NOT EDIT.
// Code generated by alioth-center/database-columns. DO NOT EDIT.
// Code generated by alioth-center/database-columns. DO NOT EDIT.

package model

type openaiclientCols struct {
	ID          string
	Description string
	ApiKey      string
	Endpoint    string
	Weight      string
	Balance     string
	CreatedAt   string
	UpdatedAt   string
}

var OpenaiClientCols = &openaiclientCols{
	ID:          "id",
	Description: "description",
	ApiKey:      "api_key",
	Endpoint:    "endpoint",
	Weight:      "weight",
	Balance:     "balance",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
}
