// Code generated by alioth-center/database-columns. DO NOT EDIT.
// Code generated by alioth-center/database-columns. DO NOT EDIT.
// Code generated by alioth-center/database-columns. DO NOT EDIT.

package model

type openaiclientbalanceCols struct {
	ID                  string
	ClientID            string
	BalanceChangeAmount string
	BalanceRemaining    string
	Action              string
	Reason              string
	CreatedAt           string
}

var OpenaiClientBalanceCols = &openaiclientbalanceCols{
	ID:                  "id",
	ClientID:            "client_id",
	BalanceChangeAmount: "balance_change_amount",
	BalanceRemaining:    "balance_remaining",
	Action:              "action",
	Reason:              "reason",
	CreatedAt:           "created_at",
}
