// Code generated by alioth-center/database-columns. DO NOT EDIT.
// Code generated by alioth-center/database-columns. DO NOT EDIT.
// Code generated by alioth-center/database-columns. DO NOT EDIT.

package model

type whisperuserCols struct {
	ID        string
	Email     string
	ApiKey    string
	Balance   string
	Role      string
	Language  string
	AllowIps  string
	CreatedAt string
	UpdatedAt string
}

var WhisperUserCols = &whisperuserCols{
	ID:        "id",
	Email:     "email",
	ApiKey:    "api_key",
	Balance:   "balance",
	Role:      "role",
	Language:  "language",
	AllowIps:  "allow_ips",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}
