// Code generated by alioth-center/database-columns. DO NOT EDIT.
// Code generated by alioth-center/database-columns. DO NOT EDIT.
// Code generated by alioth-center/database-columns. DO NOT EDIT.

package model

type whisperuserpermissionCols struct {
	ID        string
	UserID    string
	ModelID   string
	CreatedAt string
}

var WhisperUserPermissionCols = &whisperuserpermissionCols{
	ID:        "id",
	UserID:    "user_id",
	ModelID:   "model_id",
	CreatedAt: "created_at",
}
