http_engine:
  serve_url: '/v1'
  serve_addr: '0.0.0.0:10000'
logger:
  log_to_file: true
  log_split: true
  log_directory: './log'
  log_level: 'info'
bloom_filter:
  enable: true
  filter_size: 1000000
  false_rate: 0.0001
database:
  host: 'localhost'
  port: 65432
  username: 'postgres'
  password: 'lhins-f4rnk6cm'
  database: 'akasha_whisper'
app:
  max_token: 128000
  management_token: 'E43775B2-853B454F-A060CD9A-EBB51FF6'