http_engine:
  serve_url: '/v1' # serve url, must start with '/' and end without '/'
  serve_addr: '0.0.0.0:10000' # serve address, must be ip:port
  enable_management_apis: true # enable management apis, if set to false or unset, management apis will not serve
logger:
  log_to_file: true # log to file, set to false means log to stdout
  log_split: true # split log file by day, log file name will be like '2021-01-01_akasha_whisper_logs_stdout.jsonl'
  log_directory: './log' # log directory, must be created before starting, or it will panic the program
  log_level: 'info' # enum: debug, info, warn, error, panic, fatal
  log_file_suffix: '_stdout.jsonl' # log file suffix, must start with '_' and end with extension, default is '_akasha_whisper_logs_stdout.jsonl'
bloom_filter:
  enable: true # enable bloom filter
  filter_size: 1000000 # bloom filter size
  false_rate: 0.0001 # false positive rate
database:
  driver: 'mysql' # enum: mysql(>= 5.7), postgres(>= 9.6), sqlite(>= 3.9)
  host: '127.0.0.1' # example: db.yourdomain.com, 192.168.1.1, ./data/sqlite.db(only for sqlite)
  port: 3306 # example: 3306, 5432, 0(only for sqlite)
  username: 'your_username' # example: root, postgres (empty only for sqlite)
  password: 'your_password' # example: 123456, empty(only for sqlite)
  database: 'your_database' # example: test, empty(only for sqlite)s
app:
  max_token: 128000 # global max token, must be greater than 0
  management_token: 'your_management_token' # management token, must be set, empty means disable management apis
  price_token_unit: 1000 # price token unit, must be greater than 0, means if $5 = 1M tokens, your price_token_unit = 1000000, and prompt_price or completion_price = 5